# Generated by Django 4.0.5 on 2022-07-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
