# Generated by Django 4.0.5 on 2022-07-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_familia_hoy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='anio_de_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='familia',
            name='hoy',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
