# Generated by Django 4.0.5 on 2022-07-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alter_familia_anio_de_nacimiento_alter_familia_hoy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cancion', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
            ],
        ),
    ]
