# Generated by Django 4.0.5 on 2022-07-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('arte', models.CharField(max_length=50)),
            ],
        ),
    ]
