# Generated by Django 4.0.5 on 2022-07-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_artista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_album', models.CharField(max_length=50)),
                ('creador', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
            ],
        ),
    ]
